ARG NODE_VERSION=20.16.0

FROM node:${NODE_VERSION}-alpine

## Create app directory
RUN mkdir /app
WORKDIR /app

## Install app dependencies
COPY package.json /app/
RUN npm install

# Bundle app source
COPY . /app

## tell the port number the container should expose
EXPOSE 3001

## run the application
CMD ["npm", "run", "dev"]